service: dnacevents

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  contentEncoding:
    minimumCompressionSize: 860

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ${opt:region, 'ap-southeast-1'}
  environment:
    REGION: ${self:custom.region}
    STAGE: ${self:custom.stage}

functions:
  app:
    handler: main.handler
    events:
    - http: ANY /
    - http: 'ANY {proxy+}'


plugins:
  - serverless-content-encoding
  - serverless-offline
